name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Use the .NET version your project targets

    - name: Install dependencies
      run: dotnet restore TournamentOrganizer-Desktop/TournamentOrganizer-Desktop.csproj

    - name: Build
      run: dotnet build TournamentOrganizer-Desktop/TournamentOrganizer-Desktop.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test TournamentOrganizer-Desktop/TournamentOrganizer-Desktop.csproj --no-restore --verbosity normal

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Use the .NET version your project targets

    - name: Install dependencies
      run: dotnet restore TournamentOrganizer-Desktop/TournamentOrganizer-Desktop.csproj

    - name: Build
      run: dotnet build TournamentOrganizer-Desktop/TournamentOrganizer-Desktop.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test TournamentOrganizer-Desktop/TournamentOrganizer-Desktop.csproj --no-restore --verbosity normal
